{% set name = "marINvaders" %}
{% set version = "0.3.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/marinvaders-{{ version }}.tar.gz
  sha256: d15e39f203951ead0a16a6dba332d73bd9a8c3fe35f7f3245585834a62ed08bc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - beautifulsoup4
    - cached-property
    - descartes
    - geopandas
    - matplotlib-base
    - numpy
    - pandas
    - python >=3.7
    - requests
    - shapely
    - openpyxl
    - pytables
    - tqdm
    - xlrd


test:
  imports:
    - marinvaders
    - marinvaders.util
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/dlab-indecol/marinvaders
  summary: The marinvaders (Marine Invaders) is tool to process data on marine invasive species from existing databases
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - konstantinstadler
    - rlonka
